### ISSUE TITLE
kind of a bug

### ISSUE THREAD

**Issue by CharCharthemonkey** [DashieDev/DoggyTalentsNext#10]
basically i lost my 1st dog so i tried to creative summon it to me only to realize that just makes a new dog so now im stuck with a dog that cant even work and cant even be killed so help pls

**Comment by DashieDev** [comment]
Could you pleass further describe your issues ?

**Comment by CharCharthemonkey** [comment]
1st issue is the dog i originally started with wouldnt teleport with me after it somehow managed to teleport to me from over 4000+ blocks away 

2nd issue due to the 1st one not spawning i tried to summon it back to me but wound up with a new dog that was Unisex and un useable

3rd issue tried to kill the 2nd dog after i managed to walk my 1st one back over 4000+ blocks but it cant be killed even dropping it in a pool of lava and it just swims with no abilities or anything so info pls

4th issue i turned off immortality to kill the cheated in busted doggo and it cant even die so

**Comment by DashieDev** [comment]
3th and 4th i can see that your dog is in Incapacitated Mode before you switch off Immortality, you need to make the dog recover first or you can kill him via commands
1st a d 2nd issues i cant sesms to get what's going on, like what do you mean by "spawning"? Could you please provide more info? Maybe recordings if possible.

**Comment by CharCharthemonkey** [comment]
basically for 1 and 2 i was out exploring and left my doggo at my main base i teleport back via waystone to empty my inventory and the doggo rushes me so i didnt realize at the time and somehow it teleported with me away from my base but by time i realized it i tried to send it home via the same way it came with me hence 2 happening

**Comment by DashieDev** [comment]
I am still not quite get number 2 yet tbh ..... Can you demostrate by video or sth ?
If you are ok and ready, you can upload the video here
https://drive.google.com/drive/folders/1Tl0uieGoGxuGt-Vxz-J07SjKdsxK2lu3

**Comment by CharCharthemonkey** [comment]
for 2 its nothing cause its a bug with the teleport mod in question called Waystones as for the rest i still have the issue
