### ISSUE TITLE
Dog beds cause crash on chunk load

### ISSUE THREAD

**Issue by Thatfoxyoudontknow** [DashieDev/DoggyTalentsNext#101]
Friend in server placed a dog bed, no crash.
I load in the chunk the dog bed is in, crash.
2 other people load in the chunk and also crash.
removing the mod and removing the place the bed was in removes the crash.

not sure why here is the paste bin: https://pastebin.com/S564SiYB

**Comment by DashieDev** [comment]
I camt access pastebin for some reason
But probably if it is something about the no such method "VaniilaModelEncoder.emitBlockQuads" sth im fabric then it is a change in the fabric api that caused the crash, DTN Fabric 1.18.29 will fix this

**Comment by Thatfoxyoudontknow** [comment]
fabric launcher, 
oh the mod list might be important:

AnvilNever TooExpensive-fabric-1.21-1.2.jar
AxesAreWeapons-1.9.1-fabric-1.21.jar
bclib-21.0.10.jar better-nether-21.0.9.jar
cardinal-components-api-6.1.1.jar
cloth-config-15.0.128-fabric.jar
coroutil-fabric-1.21.0-1.3.7.jar
customizableelytra-fabric-2.2.6+1.21.jar
dragonloot-1.1.6.jar
EasyMagic-v21.0.2-1.21-Fabric.jar
fabric-api-0.102.0+1.21.jar
ForgeConfigAPIPort-v21.0.8-1.21-Fabric.jar
ftb-essentials-fabric-2100.1.0.jar
goldenhopper-fabric-1.21-1.5.3.jar
jamlib-fabric-1.0.11+1.21.jar
healpgood-1.4.1.jar
lootintegrations-fabric-1.21-3.7.jar
mcw-lights-1.1.1-mc1.21fabric.jar
memorysettings-fabric-1.21-5.5.jar
monolib-fabric-1.21-1.3.0.jar
Necronomicon-Fabric-1.4.2.jar
polymer-bundled-0.9.9+1.21.jar
reacharound+1.21-1.3.0.jar
Searchables-fabric-1.21-1.0.5.jar
supermartijn642corelib-1.1.17-fabric-mc1.21.jar
travelersbackpack-fabric-1.21-10.0.6.jar
Waxable Coral-fabric-1.21-2.0.1.jar
[Fabric] Armadillo Scute Armor - MC 1.21 - 1.0.1.jar
appleskin-fabric-mc1.21-3.0.5.jar
azurelib-fabric-1.21-2.3.15.jar
beautify-1.2.1+1.21.jar
betterstats-3.12.5+fabric-1.21.jar
chipped-fabric-1.21-4.0.0.jar
Clumps-fabric-1.21-18.0.0.2.jar
crawl-0.13.0.jar
CustomPlayerModels-Fabric-1.21-0.6.17d.jar
DTNPaletteOfPaws[Fabric]-1.21-1.2.jar
elytraslot-fabric-9.0.0+1.21.jar
fabric-language-kotlin-1.12.0+kotlin.2.0.10.jar
formations-1.0.2-fabric-mc1.21.jar
ftb-library-fabric-2100.1.4.jar
GrassOverhaul-MC1.21-Fabric-1.0.0.jar
 horizontal_glass_panes-1.21-fabric-3.0.0.jar
jei-1.21-fabric-19.7.0.92.jar
Lootr-Fabric-1.21-0.9.35.88.jar
mcw-paths-1.0.5fabric-mc1.21.jar
memoryusagetitle-fabric-1.0.0.jar
more_beautiful_torches-merged-1.21-3.0.0.jar
Neruina-2.1.1-fabric+1.21.jar
potionsauce-1.21-r1.jar
resourcefulconfig-fabric-1.21-3.0.3.jar
shulkerdropstwo-1.21.0-3.4.jar 
tcdcommons-3.12.3+fabric-1.21.jar
trimeffects-fabric-1.21-1.3.1.jar 
waystones-fabric-1.21-21.0.8.jar
additional_lights-fabric-1.21-2.1.10.jar
architectury-13.0.6-fabric.jar
balancedrecall-1.0.6.jar
better_climbing-fabric-3.jar 
blockus-2.9.1+1.21.jar
chunkloaders-1.2.8-fabric-mc1.21.jar
collective-1.21.0-7.80.jar
Creeperoverhaul-fabric-1.21-4.0.4.jar
darksmelting-fabric-1.21-1.1.5.jar
dungeonz-1.0.6.jar
EpheroLib-FABRIC-1.2.0-1.21.jar
firstperson-fabric-2.4.4-mc1.21.jar
formationsnether-1.0.5.jar
geckolib-fabric-1.21-4.5.8.jar
 graves-3.4.3+1.21.jar
incapacitated-fabric-1.21-1.6.1.jar
 just-hammers-fabric-21.0.2.jar
 mcw-doors-1.1.1fabric-mc1.21.jar 
mcw-roofs-2.3.1-mc1.21fabric.jar 
midnightlib-fabric-1.5.7.jar
 moreoverlays-1.23.0.1-fabric.jar
netherportalfix-fabric-1.21-21.0.2.jar
PresenceFootsteps-1.10.0+1.21.jar
resourcefullib-fabric-1.21-3.0.9.jar
smoothchunk-fabric-1.21-3.6.jar
the_bumblezone-7.6.22+1.21-fabric.jar
trinkets-3.10.0.jar
worldweaver-21.0.11.jar
alternate-current-mc1.21-1.8.0.jar
artifacts-fabric-12.0.4.jar
balm-fabric-1.21-21.0.14.jar
betterchunkloading-fabric-1.21-4.4.jar
chunksending-fabric-1.21-2.8.jar
comforts-fabric-9.0.0+1.21.jar
BuildGuide-1.21-0.4.1.jar
Croptopia-1.21-FABRIC-3.0.9.jar 
DoggyTalentsNext[Fabric]-1.21-1.18.27.jar
dusk-fabric-1.21-3.7.jar
expanded-trident-enchanting-1.0.10.jar 
fixedanvilrepaircost-1.21.0-3.4.jar
 formationsoverworld-1.0.4.jar
gigeresque-fabric-1.21-0.6.6.jar 
grind-enchantments-3.2.2+1.21-rc1.jar 
InventoryProfilesNext-fabric-1.21-2.0.4.jar 
Leaves BeGone-v21.0.0-1.21-Fabric.jar 
mcw-fences-1.1.2-mc1.21fabric.jar 
mcw-trapdoors-1.1.3-mc1.21fabric.jar
mine-spawners-1.0.jar
MouseTweaks-fabric-mc1.21-2.26.jar
oxidized-1.8.3.jar
PuzzlesLib-v21.0.19-1.21-Fabric.jar 
respawnablepets-1.21-r1.jar
Structory Towers_1.21_v1.0.7.jar
toms_trading_network-fabric-1.21-0.3.0.jar 
underwaterenchanting-1.21.0-2.9.
jar xp_storage-1.5.10+1.21.jar
alwaysawitherskull-1.21.0-3.5.jar
athena-fabric-1.21-4.0.0.jar
BambooEverything-fabric-21.0.2+mc1.21.jar
better-end-21.0.6.jar
CameraOverhaul-1.4.1-fabric-universal.jar
clientcrafting-fabric-1.21-1.8.jar
Controlling-fabric-1.21-18.0.4.jar
cupboardfabric-1.21-2.7.jar
 dragonfight-fabric-1.21-4.6.jar
dynamiclights-v1.8.3-mc1.17x-1.21x-mod.jar 
Explorify v1.6.1 f10-48.jar 
FlowerPatch-fabric-1.21-7.0.1.jar
framework-fabric-1.21-0.9.0.jar
globalpacks-fabric-1.21-21.0.0.jar
handcrafted-fabric-1.21-4.0.1.jar
Jade-1.21-Fabric-15.1.5.jar
 libIPN-fabric-1.21-6.0.2.jar
mcw-furniture-3.3.0-mc1.21fabric.jar
mcw-windows-2.3.2-mc1.21fabric.jar
mob_armor_trims-2.4.0+1.21-fabric.jar
NaturesCompass-1.21-2.2.6-fabric.jar
Pehkui-3.8.3+1.14.4-1.21.jar
randombonemealflowers-1.21.0-4.6.jar
rightclickharvest-fabric-4.3.1+1.21.jar
supermartijn642configlib-1.1.8-fabric-mc1.21.jar
totw_modded-fabric-1.21-1.0.5.jar
watut-fabric-1.21.0-1.1.3.jar

**Comment by Thatfoxyoudontknow** [comment]
> I camt access pastebin for some reason But probably if it is something about the no such method "VaniilaModelEncoder.emitBlockQuads" sth im fabric then it is a change in the fabric api that caused the crash, DTN Fabric 1.18.29 will fix this

ah thank you.
