### ISSUE TITLE
Doggy talents dogs not able to enter boats?

### ISSUE THREAD

**Issue by nomoreinternetforme** [DashieDev/DoggyTalentsNext#108]
Is there something im missing, or are they not allowed on boats? I've tried rowing into them, pushing them into it, pushing the boat into them, and placing them on the boat, nothing works. This happens with modded boats and vanilla boats alike. Is there a way to fix this?

**Comment by DashieDev** [comment]
This feature is intended to prevent accidental mount, to enable the dog to automatically enter the boat, turn on Auto Mount in the Dog Menu
