### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by CharCharthemonkey** [DashieDev/DoggyTalentsNext#11]
if possible can the doggy torch skill be changed to light level 0 or 1 even instead of it placing on light 7 pls since mobs no longer spawn on 7 but will from below 1 pretty pls

**Comment by DashieDev** [comment]
I don't think this is a practical solution because what the talents do is solely allow dogs to place torches. And currently, the light level the torches produce is static and completely depends on vanilla, and DT currently has no control over it.
