### ISSUE TITLE
Not compatible with Mob Lassos

### ISSUE THREAD

**Issue by ZarBrand** [DashieDev/DoggyTalentsNext#113]
Mob lassos is a mod that lets you pick up mobs and move them, it is NOT compatible with DTN. The developer for that mod is aware that they're not compatible but won't blacklist the dogs. The dogs can be picked but they can't be released from the lasso, this creates a glitched lasso and I was unable to recall my dog to the bed. I tried getting rid of the lasso, in lava, and it straight up corrupted the world. This is not a bug on your end, I'm just asking you to add a disclaimer/warning in your mod description somewhere so more people don't lose their dogs.

**Comment by DashieDev** [comment]
We did add a disclaimer in the FAQ and how to get your dog back.
https://doggytalentsnext.wiki.gg/wiki/FAQ#About_Compatibility_between_DTN_and_a_3rd-party_mod's_feature_that_stores_the_dog_in_something._(eg._Carry_On,_Portable_Mobs,_Mobs_in_a_Bucket,_Ender_Lead,...)
