### ISSUE TITLE
dependency

### ISSUE THREAD

**Issue by Smokie300zx** [DashieDev/DoggyTalentsNext#114]
i cants use the next doggy talents for forge 1.20.1 cuz it has a dependency for doggy talents even tho it dont say any on the download page and dt dont have any 1.20.1 version.... so how do i even use this ?

**Comment by DashieDev** [comment]
I dont know where you even got that information from, DTN is completely seperate from DT and definitely can and must be used without DT.

**Comment by Smokie300zx** [comment]
game says deff not, evrytime i install it is crashes an says needs required dt

**Comment by DashieDev** [comment]
Please see FAQ in [this section](https://doggytalentsnext.wiki.gg/wiki/FAQ#Before_reporting_a_Bug). Thank you.

**Comment by Smokie300zx** [comment]
Yahoo Mail - Email Simplified 
 
  On Sat, Nov 30, 2024 at 6:38 PM, ***@***.***> wrote:   


screenshot please?
