### ISSUE TITLE
[1.19.2] Biomes O Plenty Dog beds do not show up anymore, compatibility broken

### ISSUE THREAD

**Issue by NovaViper** [DashieDev/DoggyTalentsNext#14]
## Environment And Mod Information:
* Minecraft Version: 1.19.2
* Forge Version: 43.2.0
* Doggy Talents Version: 1.10.7
* Java Version: Java 17 64bit
* Operating System (OS): EndeavourOS

## Logs
[debug.log](https://github.com/DashieDev/DoggyTalentsNext/files/11095204/debug.log)

## Issue Description:
After upgrading from 1.18.2 to 1.19.2, the dog beds for Biomes O Plenty's woods do not appear anymore, the game complains that their missing in the registry and their textures are black and pink.

## Steps to reproduce:
1. Upgrade from 1.18.2 to 1.19.2
2. Upgrade all respective mods for 1.19.2
3. Open world from 1.18.2 (or create a world in 1.19.2)
4. Bug occurs

## Additional Information:
- More Details: 
- Screenshots:

**Comment by DashieDev** [comment]
Yeah, that is expected behavior for now, back then when I was porting to 1.19.2, I temporarily left out the compatibility module to make things simpler for me ( it was my first time porting a mod actually 😅 ) that includes JEI too. I am so sorry for the inconvenience. But no worries, I will definitely add it back in the close future.

**Comment by NovaViper** [comment]
> Yeah, that is expected behavior for now, back then when I was porting to 1.19.2, I temporarily left out the compatibility module to make things simpler for me ( it was my first time porting a mod actually sweat_smile ) that includes JEI too. I am so sorry for the inconvenience. But no worries, I will definitely add it back in the close future.

Ah, ok! I'd be willing to do testing with the mod aswell if needed.

**Comment by DashieDev** [comment]
Oh wow, thanks ❤️ That will certainly help a lot! Also, I noticed you are one of the devs in the original DT (which is like .... 2 i think, alongside Percivalalb) It is very interesting to see you 😅

**Comment by DashieDev** [comment]
Update on this.
Every wood/logs variant (vanilla+other mod) is supported automatically on the newest version **1.16.3** which available across 1.19.2/1.18.2/1.20(.1) as long as the texture is placed like most of the vanilla wood does '''<namespace>:textures/block/<that_block_id>.png'''
