### ISSUE TITLE
Conductor Wand not in mod

### ISSUE THREAD

**Issue by BirdPerfect** [DashieDev/DoggyTalentsNext#16]
My dogs are where I last teleported from and I don't know where that is. I've searched the mod in creative and there is no conductor bone to recall them to me. Also, the whistle doesn't open the GUI when I "Shift + Rt Click".

**Comment by DashieDev** [comment]
Could you please further clarify your problems ? 
What happened when you shift+click the Whistle ? Anything happens ? 
Also can you describe how you search ? Like what does it shows ?

**Comment by DashieDev** [comment]
Closed as no further information is gathered.
