### ISSUE TITLE
I don't know what to do

### ISSUE THREAD

**Issue by Winterwulff** [DashieDev/DoggyTalentsNext#17]
My dog hit the ground and died but can't respond him and he's just frozen on my screen crying at -63 hunger and I can't feed him or interact with him.

**Comment by DashieDev** [comment]
Your dog is incapacitated. You can see the hunger will slowly regen to 0, at which where the dog will be available again. You can learn more [here](https://github.com/DashieDev/DoggyTalentsNext/wiki/Immortal-Dogs)
