### ISSUE TITLE
Dog dissappears after logging off while riding boat

### ISSUE THREAD

**Issue by HunterNacho** [DashieDev/DoggyTalentsNext#18]
I disconnected while riding a boat with my dog. After joining the server again, the dog was gone. The radar points to the spot where I initially logged out and the conducting bone does not work for it. Both items recognize the dog exists and it still owns a bed.

Minecraft Version: 1.19.2
Mod version: 1.11.2

Steps to reproduce:
1. Set a boat somewhere in the world
2. Get the dog to ride the boat by making it walk close to it
3. Ride the boat
4. Disconnect / Save and quit
5. Join the world again

![2023-05-06_18 57 30](https://user-images.githubusercontent.com/2405642/236650058-1477cb83-8bb8-4b2a-9c3d-228e798f3af8.png)
![2023-05-06_19 02 01](https://user-images.githubusercontent.com/2405642/236650060-7eb0dd52-5816-46b8-acfc-eb22fc2cc937.png)

**Comment by DashieDev** [comment]
Fixed and pushed in ```1.12.2``` for all versions of mc.
I am deeply sorry for the corruption 😥
