### ISSUE TITLE
dogs don't breed

### ISSUE THREAD

**Issue by yollk** [DashieDev/DoggyTalentsNext#19]
hey! I've used the breeding bone, my doggos are male and female and there are no puppies. am I doing sth wrong?

**Comment by DashieDev** [comment]
Unfortunately, i can't seem to replicate the bug by just breeding the dog on my end, can you further describe your issues ?

**Comment by yollk** [comment]
im not sure what else to tell you, honestly. i use the breeding bone on
dogs and nothing happens

**Comment by DashieDev** [comment]
Feel free to provide more information such as : 
+ Do you have any other mods installed ? Did you tried with just DT installed ? 
+ Did you tested it on a new world ?

**Comment by DashieDev** [comment]
Closed as no further information is gathered.
