### ISSUE TITLE
Immortal dogs

### ISSUE THREAD

**Issue by RubyDaRoses** [DashieDev/DoggyTalentsNext#20]
Hello, I tried for 2 hours to search what did you change for bringing back immortal dogs, I didn't managed to understand, can you please do the same or at least explain me how to do the same on the 1.18.2 version of the mod? Please ;-;

**Comment by DashieDev** [comment]
DoggyTalentsNext currently doesn't support 1.18.2. The version you are referring to is in the old project, which is not owned or managed by me, so i have no control over it.
for 1.19.2+, there is a config option for immortal dogs, which is now enabled by default. If it isn't you can switch it on by going to your world serverconfig file.
More info here [https://github.com/DashieDev/DoggyTalentsNext/wiki/Immortal-Dogs](here)
