### ISSUE TITLE
[Request] Is there any news or updates on a Fabric port of the mod?

### ISSUE THREAD

**Issue by Baylem** [DashieDev/DoggyTalentsNext#23]
I'm very interested in a 1.20 fabric port of the mod, is there any updates or news pertaining to a possible port or is there something blocking a Fabric port?

**Comment by DashieDev** [comment]
The Fabric API is missing come critical stuffs that DT relies on....  and currently i don't have the timre needed to do a Fabric Port..... That's all i can say for now, sadly
