### ISSUE TITLE
Language file bug

### ISSUE THREAD

**Issue by Vadewolf** [DashieDev/DoggyTalentsNext#27]
all the DTN specfic advancements have a issue with the descriptions shown

**Comment by DashieDev** [comment]
Currently, the advancement system is still in WIP.  So most thing are not implemented yet unfortunately

**Comment by HiddenPower167** [comment]
![2023-07-17_12 59 18](https://github.com/DashieDev/DoggyTalentsNext/assets/97117357/5b809b00-6836-4c39-b0fc-3dc3c44584d1)
![2023-07-17_13 10 57](https://github.com/DashieDev/DoggyTalentsNext/assets/97117357/d94772b9-9a83-4b61-90e3-4c551a0c52c5)
![2023-07-17_13 10 59](https://github.com/DashieDev/DoggyTalentsNext/assets/97117357/17dbf227-ddcf-4a45-87b9-bd5c119e698d)
![2023-07-17_13 11 00](https://github.com/DashieDev/DoggyTalentsNext/assets/97117357/d1540704-c036-498a-90f8-37e83ce5bd1a)

here's what the bugged advancements look like on my end (i understand it's still a wip, just wanting to help out)

**Comment by Vadewolf** [comment]
yea same i get WIP but seeing those makes us question when we did nothing in DTN specfically to get the advancements yet they popped
