### ISSUE TITLE
Dog Bed not functioning at all

### ISSUE THREAD

**Issue by Stormpuls3** [DashieDev/DoggyTalentsNext#31]
Self-explanatory. I've had no success getting the beds to work.  Any attempts just result with the instructions appearing in my chat log.

To rule out incompatibilities, I've tested in a single player game, no other mods installed. Minecraft version 1.19.2, Forge version 43.2.14.

I have a properly treated dog standing right next to the bed.
No armor on my avatar, no weapons equipped, both hands emptied. 

Expected result: the dog wanders over to the bed and claims it as its own.

And yet, it's just more instructional messages.

I picked up the mod so I would feel better having dogs as companions without death being as large of a consequence. But if I can't get the basic function of the beds to work, I may have to hold off for a while.

**Comment by Stormpuls3** [comment]
Never mind. I have learned through further experimentation that crouch-clicking is what I was supposed to do, but my crouch key is bound to a different key. The instruction should be updated as much for clarity's sake. :)

**Comment by DashieDev** [comment]
Well even without the bed, you still have immortal dogs 😉 So unless your dog is vulnerable to void damage, he cant die 😉 But you will still need to help him recover 👌
