### ISSUE TITLE
version 1.16.3 on mc version 1.20.1 has bugged advancment names

### ISSUE THREAD

**Issue by TungstenWolf** [DashieDev/DoggyTalentsNext#34]
All advancements display as this format 
![image](https://github.com/DashieDev/DoggyTalentsNext/assets/85911010/d7834540-111e-46d2-93a3-32e0a643914f)
Most also lead to a crash when getting those items

Version 1.16.3 of the mod on forge using mc version 1.20.1

**Comment by DashieDev** [comment]
Can please you further elaborate on the crash? 
Since the achievement system is WIP and are supposed to be like that but shouldnt cause a crash.
