### ISSUE TITLE
Dogs go to old bed spot

### ISSUE THREAD

**Issue by LetaStar** [DashieDev/DoggyTalentsNext#35]
Like the title, the dogs go to their old bed spot when you use the whistle. This happens when I move the beds, and I have no idea how to fix it (1.18.2)

https://github.com/DashieDev/DoggyTalentsNext/assets/69783691/535703e4-1db1-4507-801d-ac5bccb0a7c9

**Comment by DashieDev** [comment]
Currenrly the only solution is to make new beds and make the dog claim the bed again. But i am thinking of a way to improve this.

**Comment by DashieDev** [comment]
Fixed in ```1.17.1```
