### ISSUE TITLE
2 issues in 1 

### ISSUE THREAD

**Issue by Vadewolf** [DashieDev/DoggyTalentsNext#36]
basically when using the doggy food bowl the dogs wont eat from it at all no matter wat food is put into it or their happy eater skill level 

and seems you can just continuosly spam feed the dogs even when u shouldnt be able to

**Comment by Vadewolf** [comment]
ok so as of the update for 10/14/2023 the food bowl works again but the food spam is still an issue

**Comment by Vadewolf** [comment]
ok so upon further  testing it seems to only kinda work but not fully

**Comment by estebanthebad** [comment]
Can you please describe the issue in full detail? I am not a dev of this mod but I would just ignore a report like "ok so upon further testing it seems to only kinda work but not fully". Just my 2 cents.

**Comment by Vadewolf** [comment]
basically i have 7 dogs (i think) but none of them will eat from their assigned bowls at all and for some reason the food doesnt seem to stack with the matching food from my mob farms so idk if that causes them to not see it as viable food also with the fish you can continuously spam that to the dogs even after they are max hunger
