### ISSUE TITLE
19.3 version is glitching

### ISSUE THREAD

**Issue by PeachesLeeches0** [DashieDev/DoggyTalentsNext#4]
All of my dogs talents, clothes, and collars are gone.

**Comment by DashieDev** [comment]
Thanks for reporting, can you provide the log file at that particular session? 
Forge 1.19.3 and the 1.19.3 version of the mod itself is still in beta now so we can't be expecting much ...

**Comment by DashieDev** [comment]
Fixed in ```1.18.2``` perhaps.
