### ISSUE TITLE
Wiki does not say how to drop carried, incapacitated dog

### ISSUE THREAD

**Issue by estebanthebad** [DashieDev/DoggyTalentsNext#40]
Dog got incpacitated, I picked it up with a bone, like described in the wiki. Now I am at home, in a safe place, the dog bed at the ready but for the love of the universe I can not figure out how to drop the dog into the bed.

Can you please update the wiki, so it tells the following:
1. How to drop a carried, incapacitated dog on the ground.
2. How to drop a carried, incapacitated dog into a dog bed.

Thanks a lot!

**Comment by estebanthebad** [comment]
Ok, so I found out by myself.

To drop a carried dog one has to look up and right-click it with a bone again. The incapacitated dog then falls to the ground. It is also possible to do that, when standing on a dog bed. Then the dog falls on the dog bed. But does it then also count to be **_in_** the dog bed?

Thanks!
(Please still update the wiki. This cost me like one hour. ^^ )

**Comment by Kavaltheone** [comment]
On version 1.18.8 for Fabric it don't work T_T 
The only way to drop dog from head is to reload.

**Comment by DashieDev** [comment]
I am so sorry for the inconvinence, i will fix this in DTN 1.18.9 for Fabric

**Comment by Kavaltheone** [comment]
Thanks. And actually I was testing "Bed Finder" talent. Could you please check if everything ok with it? I saw GIF on wiki - it was a yellow outline. But I see no outline on Dog bed or my bed (they are near). My bed is bound to me, Dog's bound to my dog, tried talent lvl1 and lvl 5. Also tested with wall between beds and me and with clear line sight.
While testing had to relogin to remove dog from my head couple of times. Just for test tried dog with full health and when in incapacitated state - nothing worked (empty hand, bone in hand, clicking on land, on bed, on dog while on head, on my second dog)
No matter what, this mod is awesome. Thanks for bringing it on Fabric version.

**Comment by DashieDev** [comment]
Update for the "Dismount problem": It is also fixed in the upcoming 1.18.9.

**Comment by Kavaltheone** [comment]
Confirm. Problem solved (version 1.18.10 Fabric)
