### ISSUE TITLE
My bed clones dogs and the conducting bone doesn't work

### ISSUE THREAD

**Issue by M25R4PTOR** [DashieDev/DoggyTalentsNext#43]
I have a dog with his assigned bed (He made the animation on the bed), when I click on the bed a duplicate of my dog appears and the conducting bone only works to bring the dog with me, but it does not work to go to bed.

**Comment by DashieDev** [comment]
Do you have any other mods which do something about the respawning mechanic of the dog beside DTN?

**Comment by M25R4PTOR** [comment]
I have a lot of mods installed, but I think it might be Domestication-Innovation-Mod-Forge-1.20.1.jar


**Otherwise here you have a complete list of all the installed mods:**
aether-1.20.1-1.0.0-beta.1.3-neoforge.jar
alexsmobs-1.22.6.jar
Aquaculture-1.20.1-2.5.0.jar
architectury-9.1.12-forge.jar
athena-forge-1.20.1-3.1.1.jar
balm-forge-1.20.1-7.1.4.jar
bettercombat-forge-1.7.4+1.20.1.jar
BiomesOPlenty-1.20.1-18.0.0.598.jar
BlackwolfLibrary-1.20.1-1.0.2-[FORGE].jar
Bookshelf-Forge-1.20.1-20.0.5.jar
BotanyPots-Forge-1.20.1-13.0.17.jar
buildinggadgets2-1.0.5.jar
cfm-forge-1.20.1-7.0.0-pre36.jar
chipped-forge-1.20.1-3.0.1.jar
citadel-2.4.5-1.20.1.jar
cloth-config-11.1.106-forge.jar
Clumps-forge-1.20.1-12.0.0.3.jar
cluttered-2.1-1.20.1.jar
comforts-forge-6.3.3+1.20.1.jar
Connectivity-Mod-Forge-1.19.4.jar
controllable-forge-1.20.1-0.20.3.jar
cosmeticarmorreworked-1.20.1-v1a.jar
curios-forge-5.3.5+1.20.1.jar
Decorative+Blocks-forge-1.20.1-4.0.2.jar
DivineRPG-1.10.6.1.jar
DoggyTalentsNext-1.20.1-1.17.1.jar
Domestication-Innovation-Mod-Forge-1.20.1.jar
dragonmounts-1.20.1-1.1.5.b3.jar
DramaticDoors-Forge-1.20.1-2.3.8.jar
Dungeon+Crawl-1.20.1-2.3.14.jar
DungeonsArise-1.20.1-2.1.57-release.jar
DustrialDecor-1.3.4-1.20.jar
EnchantmentDescriptions-Forge-1.20.1-17.0.8.jar
epicpaladins-0.1.1-1.20.1-forge.jar
epicsamurai-0.0.26.3-1.20.1-forge.jar
exlinefurniture-forge-1.20.1-2.7.3.jar
exoticbirds-1.20.1-1.0.0.jar
explorify-v1.3.0-mc1.20u1.20.1.jar
framework-forge-1.20.1-0.6.16.jar
friendsandfoes-forge-mc1.20.1-1.9.7.jar
geckolib-forge-1.20.1-4.2.3.jar
handcrafted-forge-1.20.1-3.0.1.jar
hole_filler_mod-1.2.8_mc-1.20.1_forge.jar
invhud.forge.1.20.1-3.4.18.jar
Jade-1.20.1-forge-11.6.1.jar
jei-1.20.1-forge-15.2.0.27.jar
journeymap-1.20.1-5.9.15-forge.jar
magicvibedecorations-HALLOWEEN+1.5.0+1.20.1+forge.jar
mavapi-1.1.3-mc1.20.1.jar
mavm-1.2.4-mc1.20.jar
mcw-bridges-2.1.1-mc1.20.1forge.jar
mcw-doors-1.1.0forge-mc1.20.1.jar
mcw-fences-1.0.7-mc1.20.1forge.jar
mcw-furniture-3.2.0-mc1.20.1forge.jar
mcw-lights-1.0.6-mc1.20.1forge.jar
mcw-paths-1.0.3forge-mc1.20.1.jar
mcw-roofs-2.2.4-mc1.20.1forge.jar
Measurements-forge-1.20.1-2.0.0.jar
MOAdecor+ART+1.20.1.jar
MOAdecor+BATH+1.20.1.jar
MOAdecor+COOKERY+1.20.2.jar
MOAdecor+GARDEN+1.20.1.jar
MOAdecor+LIGHTS+1.20.1.jar
MOAdecor+SCIENCE+1.20.1.jar
MOAdecor+TOYS+1.20.1.jar
MobCapturingTool-forge-1.20.1-3.0.2.jar
MonsterPlus-Forge1.20.1-v1.1.6.1.jar
moonlight-1.20-2.8.49-forge.jar
MoreBows-1.0.13+1.20.x.forge.jar
morebowsandarrows-1.0.0.jar
MoreDecorativeBlocks-1.20.1-1.0.4-[FORGE].jar
mythicmounts-20.1-7.4.2-forge.jar
NaturesCompass-1.20.1-1.11.2-forge.jar
Neat-1.20-35-FORGE.jar
netherportalfix-forge-1.20-13.0.0.jar
Patchouli-1.20.1-81-FORGE.jar
player-animation-lib-forge-1.0.2-rc1+1.20.jar
player_companions_1.20-6.7.1.jar
Rats-1.20.1-8.1.1.jar
reliquary-1.20.1-2.0.36.1199.jar
repurposed_structures-7.1.7+1.20.1-forge.jar
resourcefullib-forge-1.20.1-2.1.11.jar
Rex's-AdditionalStructures-1.20.x-(v.4.2.1).jar
simple+guns+1.20.1+bugfixes.jar
simplylight-1.20.1-1.4.5-build.49.jar
snuffles-1.0.7.jar
sophisticatedbackpacks-1.20.1-3.18.59.909.jar
sophisticatedcore-1.20.1-0.5.89.425.jar
storagedrawers-1.20.1-12.0.2.jar
Structory_1.20.2_v1.3.3.jar
supplementaries-1.20-2.6.12.jar
TerraBlender-forge-1.20.1-3.0.0.169.jar
Terralith_1.20.2_v2.4.7.jar
tombstone-8.5.5-1.20.1.jar
Waddles-1.20.1-0.9.4.jar
waystones-forge-1.20-14.0.2.jar
xtraarrows-3.0.4-forge-mc1.20.1.jar
[1.20.1-forge]-Epic-Knights-8.2.jar


**Thanks for the mod, it's awesome!**

**Comment by DashieDev** [comment]
Probably that one since a member from our team who have both of them does confirmed that duplications may occurs. Do you use any of that mod features?

**Comment by M25R4PTOR** [comment]
Yes, I love taming all possible mobs

**Comment by DashieDev** [comment]
Ah no no, i mean do you use any of that mods feature **on the dog**?

**Comment by M25R4PTOR** [comment]
On the dog only doggy talents next

**Comment by DashieDev** [comment]
Can you still reproduce the bug?

**Comment by M25R4PTOR** [comment]
Yes, when I right click on the dog's bed a duplicate always appears and the conducting bone never returns the dog to the bed (but it does bring him to me).

**Comment by DashieDev** [comment]
Can you provide a video so i can see exactly what is going on? I cant seems to replicate the bug here

**Comment by M25R4PTOR** [comment]
Sorry, I think I have found the problem. When using Mob Capturing Tool(Mod) on the dog, the dog is cloned in the bed when you right click. This happens even if the dog is outside the Mob Capturing Tool.

![image](https://github.com/DashieDev/DoggyTalentsNext/assets/32265733/dd9ef234-a4f5-4c8f-ac7c-723715234d94)

It is one of the best mods I have ever played, I would like to know if you are planning to implement a way to add our own skins to the dogs. The Arcanine skin is awesome!
Thanks for everything!

**Comment by M25R4PTOR** [comment]
If you can update the mod wiki it would be perfect.

And if the dog food bowl could be linked like the bed does visually and in the chat it would be better.

**Comment by DashieDev** [comment]
Update:
With the newest update, there is a feature called Duplication Detection which will detect everytime a dog is loaded and restored from third party storage and remove it since the dog either still present in DTN's respawn or has respawned but unloaded.
