### ISSUE TITLE
Chests on dogs are still visible when config settings are false.

### ISSUE THREAD

**Issue by fyerwire** [DashieDev/DoggyTalentsNext#44]
The config toggle for the pack puppy chests does not make the chests disappear. I tried using the config both though the file and though a mod (forge config screens) to make sure i did everything correct.

I am currently playing the latest version, 1.20.1-1.17.2, with no other mods except for "Better Dogs for DNT." and "Forge Config Screens".

**Comment by DashieDev** [comment]
Thanls for reporting, it will be fixed in the next update.
