### ISSUE TITLE
Dogs turn into Ticking Entities 

### ISSUE THREAD

**Issue by cookiehow** [DashieDev/DoggyTalentsNext#49]
I've been having my worlds crash for no reason for a few days now and all of the crash reports have been about Ticking Entities, which were all from my doggies coming from this mod. First one happened after having played in that world for about 2 weeks and the other happened just after a few hours. I opened another world to test again and after summoning a dog, 5 minute passes and my world crashes again. I love my doggies so I hope theres a way to fix this :(

heres one of the crash reports:

[crash-2023-11-21_16.52.57-server.txt](https://github.com/DashieDev/DoggyTalentsNext/files/13427591/crash-2023-11-21_16.52.57-server.txt)

**Comment by DashieDev** [comment]
Which DTN version are you using?
Probably **1.19.2** since that should be where that bug is according to my findings.
That bug should be fixed in **1.19.2-1.17.5**. You can update the mod and try again.
