### ISSUE TITLE
Doggy Talents Ticking Entity Crashing Server

### ISSUE THREAD

**Issue by Marouseum** [DashieDev/DoggyTalentsNext#50]
I host a server and what happened is that one of my members was messing around with a creature called from Alex's Mobs and what we believe happened it that a doggy talents dog got the ender flu from it. I will leave a report on both mod pages but this is the crash report. The crash report states that it is a Doggy Talents error. The server is not recoverable despite several kill all commands and removal of all effects.

[crash-2023-11-20_23.35.59-server.txt](https://github.com/DashieDev/DoggyTalentsNext/files/13443493/crash-2023-11-20_23.35.59-server.txt)

**Comment by DashieDev** [comment]
You can update the mod to 1.17.5 and it will fix it.
We are deeply sorry for the incident.

**Comment by Marouseum** [comment]
> You can update the mod to 1.17.5 and it will fix it. We are deeply sorry for the incident.

This was on 1.19.2.

**Comment by DashieDev** [comment]
I mean DTN 1.19.2-1.17.5
DTN 1.17.5 is released for all supported version.
Please report back if the problem still exists.
