### ISSUE TITLE
My dogs arent eating

### ISSUE THREAD

**Issue by xromsca** [DashieDev/DoggyTalentsNext#54]
one of my dogs ive set to wander and she teleported to me saying she was hungry, try feeding her beef, fish chicken and she just wont eat.

**Comment by DashieDev** [comment]
Which version you are on? DTN and MC?

**Comment by xromsca** [comment]
MC
i switched to an older version of the mod and now its working again. So it might be something with the newer version.

**Comment by DashieDev** [comment]
Are those item cooked? As right now the dogs are quite picky and they will refuse any meat item that has nutrition under 6 which includes uncooked meat

**Comment by xromsca** [comment]
No they were all raw uncooked food

**Comment by DashieDev** [comment]
Yeah you need to cook them first. Or you can give your dogs DTN food instead 👌

**Comment by xromsca** [comment]
Oh ok! Thank you!!
