### ISSUE TITLE
Dogs at negative points

### ISSUE THREAD

**Issue by L33L33L33** [DashieDev/DoggyTalentsNext#59]
Whenever I give my dog treats and either log out or be in game for a couple hours my dog would be at negative points depending on how many treats I gave them. Also, whenever I tried giving my dogs treats again to get them out of the negatives it never saves and it'll go back to the first time I leveled them up.

**Comment by DashieDev** [comment]
This is a known bug for 1.19.2/1.18.2 and a patch which includes a fix for 1.19.2 is released!

**Comment by DashieDev** [comment]
Fixed in **DTN 1.18.7**

**Comment by L33L33L33** [comment]
okay, thank you!
