### ISSUE TITLE
Armor / inventory / training glitch.

### ISSUE THREAD

**Issue by Plisko1** [DashieDev/DoggyTalentsNext#6]
Love the mod.  I've played it since around 1.7.   Thanks for keeping it going!  We have a 3 person 1.19.3 server.  We each have dogs.

Running Forge 44.1.0  
DTN version 1.8.1

Each of us experiences the armor, inventory and talent menu glitching at different times.  It sometimes changes with restarts, portals and death.  The glitch is a reversion to the dog with no talents and 15 points to train even though the talents are there and there are no points.  No armor is visible no inventory is available even though they are there when the glitch clears.  The skin choice stays and armor level shows in the glitched training menu.

Also, when the inventory is available the inventory button comes and goes when opening and closing the crafting book.  Can't leave the book closed if I want the dog inventory button.

We're still playing through the bugs and enjoying the mod.  We like your vision!

Log attached

[latest.log](https://github.com/DashieDev/DoggyTalentsNext/files/10348198/latest.log)

**Comment by DashieDev** [comment]
Thanks a lot for reporting, i have experienced it on my side and can confirm that there is a  client-server synchronization problem in 1.19.3 version in dev enviroment, but have not confirmed in the mainstream yet. Thanks for confirming it! ❤️ Will take a look.
Meanwhile this will not affect anything outside of you wouldn't see the changes in the client, have fun ❤️
I am very glad that you are satisfied with the mod ❤️ I spent a lot of heart and soul on it.

**Comment by DashieDev** [comment]
130a581b92fa571e33998037b06d708164edd6c1

Fixed it! I am going to do a few more changes and will push the update asap.
Feel free to report bugs here if you encounter them again, i appreciate it ❤️

**Comment by DashieDev** [comment]
Fixed and released in ```1.8.2```.

**Comment by DashieDev** [comment]
Reopen as i can see there is still one problem i haven't addressed (The inventory button)

**Comment by DashieDev** [comment]
https://github.com/DashieDev/DoggyTalentsNext/commit/b686e0d6a1fb22e94bea02de65644ef1865f8628

The improper inventory button rendering was my silly mistake ... I am an idiot ...

**Comment by DashieDev** [comment]
FINALLY fixed in ```1.9.1```
