### ISSUE TITLE
bug for DTN

### ISSUE THREAD

**Issue by Vadewolf** [DashieDev/DoggyTalentsNext#60]
seems doggy talents next over writes the fried egg recipe so fried eggs from farmers delights doesnt get made

**Comment by DRACTION** [comment]
If I understand you correctly, the recipes are the same, but the results are different.
As a temporary solution, write a KubeJS or CraftTweaker script to change the recipe.
Or via datapack...

**Comment by Vadewolf** [comment]
yes the recipes are the same but the outputs are different cause DTN makes that weird egg thing and farmers delight makes fried egg

**Comment by Vadewolf** [comment]
ok so guess ure unwilling to fix a compat issue between DTN and farmers delights?

**Comment by Vadewolf** [comment]
thank you cause honestly this mod is so much fun and even OP but id hate to of dropped it due to a compat issue
