### ISSUE TITLE
giving Training Treat crashes me out of my server

### ISSUE THREAD

**Issue by strangelyconvinced** [DashieDev/DoggyTalentsNext#69]
Hello, giving a training treat to my pet dog crashes me out and gives me this error: 

Internal Exception: java.lang.ArrayIndexOutofBoundsException: Index 11546150 out fo bounds for length 4

![image](https://github.com/DashieDev/DoggyTalentsNext/assets/163507698/4951e0de-829f-46e2-8e06-1c5f8b75ec18)

Server is Fabric 1.20.1

**Comment by strangelyconvinced** [comment]
![image](https://github.com/DashieDev/DoggyTalentsNext/assets/163507698/2f75035d-0f20-4a76-97f6-0a30f6bbc9ce)

Also managed to fix it by re-installing server, but now whenever I level up skills this is what happens

**Comment by DashieDev** [comment]
This is a known bug on the Fabric Port of DTN, it is fixed actually and i will push it in DTN1.18.9

**Comment by DashieDev** [comment]
Fixed in DTN1.20.1-1.18.9 for Fabric
