### ISSUE TITLE
texture addons through server 

### ISSUE THREAD

**Issue by StressedHelp** [DashieDev/DoggyTalentsNext#7]
I've been wanting to use mods for a while now, and was finally able to set up a server to do so with friends. I wanted to add my own texture for the coats of the dogs, but I cannot find the assets folder. All of my mods are through the server instead of in a folder on my computer. I am using serverminer, does anyone else use this and can they help me find this folder? Thanks! :)

**Comment by DashieDev** [comment]
The assets folder for doggy talents is in the mod's jar at
```assets\doggytalents\textures\entity\dog\custom\```.
There is some missing texture there and you can fill in the gap, or you can directly override the existing one. But remember to do the same thing on all clients ! Also make sure the names are intact.

**Comment by StressedHelp** [comment]
Thank you so much :)
