### ISSUE TITLE
fixed

### ISSUE THREAD

**Issue by chimeracon** [DashieDev/DoggyTalentsNext#72]
One of my dogs I'm struggling to try to retrieve. I took him a distance away from my base and he keeps popping in and out of existence when I go back to the chunk that he was left at. The model is just not there. He'll show up for a few seconds and then vanish again.
I keep using /tp @e to get him to come back and he just vanishes again. I've tried to use a kill command so I can respawn him at my base, the chat said that he died but the bed isn't working. When I used the /tp command again he came back. 
I can't even open the menu long enough to try to fiddle with his settings as he just vanishes after a few seconds. 
This is kind of driving me insane, I don't know what's going on?? 
Edit; I finally managed to get the dog home and turned off patrol mode, and he's no longer disappearing. So I think there's a bug with that feature specifically.

**Comment by DashieDev** [comment]
This eems like an expected behaviour with patrol mode.
In Patrol Mode, your dog will not leave an area around the position where the dog is last set to patrol. If your dog get far enough from that center, he will try to teleport back.
