### ISSUE TITLE
Проблема совместимости с Forbidden and Arcanus

### ISSUE THREAD

**Issue by MaraDra** [DashieDev/DoggyTalentsNext#78]
Good afternoon. I have a mod 
Forbidden and Arcanus, which contains the Quantum Trapper item, which allows you to transport mobs. Since I (this is stupid, of course, but still), get attached to my pets even in the game, this item often helped me out when I needed to quickly and safely drag someone or temporarily “mothball” them. But today it turned out that the catcher works strangely with the dogs from your mod. He doesn't release them into the world. At the same time, an inscription remains in the catcher itself that the dog is there. Once, by clicking on the bed, I managed to release the dogs directly onto it, but repeating the action for the test, I got the same result - there was no dog, although it remained recorded in the catcher. 
I'm not sure who to contact with this problem - you or the author of Forbidden and Arcanus?
I really don’t want to over such a trifle, reduce the use of the mod, it’s really wonderful, but I can’t overcome myself and stop worrying about the pets)
(Sorry for my English, this post was written using Google)

**Comment by DashieDev** [comment]
This behaviour is expected as to prevent duplications.
You can still however get your dog back via the Dog Bed if you accidentally "trap" it.
We do provide alternative to keeping your dog with you.
https://github.com/DashieDev/DoggyTalentsNext/issues/52

**Comment by MaraDra** [comment]
Thank you for the quick response. Of course, it’s a pity that this function is necessary, but nothing can be done. I'll try to get used to other methods. Your mod is excellent and brings a lot of joy, so I will be happy to wait for new updates. Thank you)
