### ISSUE TITLE
(1.18.2) Can't put lead on dog

### ISSUE THREAD

**Issue by CircusSeal** [DashieDev/DoggyTalentsNext#83]
Or use a mob catcher device from the Mob Catcher mod. Since they both require right-clicking the mob, it just makes the dog sit down.

This also means I can't attach my Better Dogs x Doggy Talents Next dog to a sled from Snowy Spirits.

**Comment by DashieDev** [comment]
This is expected behaviour as Vanilla Lead A.I system may interfere with DTN''s AI system.
