### ISSUE TITLE
[1.21] Doggy Talent Crashing with Neo Forge

### ISSUE THREAD

**Issue by Periam** [DashieDev/DoggyTalentsNext#85]
After installing the mod, the game will not launch.

MC 1.21
NeoForge 21.0.16
DoggyTalentsNext-1.21-1.18.18-beta2

Crash Log:
[crash-2024-06-18_11.42.00-fml.txt](https://github.com/user-attachments/files/15888279/crash-2024-06-18_11.42.00-fml.txt)

**Comment by DashieDev** [comment]
This has been resolved with the third beta. Please update to tix this.

**Comment by Periam** [comment]
it works. thanks.
