### ISSUE TITLE
1.21 dogs dissapear

### ISSUE THREAD

**Issue by GlauberBlox** [DashieDev/DoggyTalentsNext#92]
bro the dogs is dissapearing in neoforge 21.0.111

video: https://github.com/user-attachments/assets/4da396e6-00b5-4312-bdab-6f2c03b75dcf

image:
![image](https://github.com/user-attachments/assets/54f39113-2283-45ea-be32-00aebff153d0)

**Comment by DashieDev** [comment]
Currently the latest DTN support version only support .78.
Although we will build against the latest version of neo in the next update

**Comment by GlauberBlox** [comment]
okey i will wait

**Comment by DashieDev** [comment]
DTN 1.18.21 has been released for neo 21.0.113

**Comment by GlauberBlox** [comment]
TYYYY
