### ISSUE TITLE
(1.21 Fabric) Crafting Recipes Not Working

### ISSUE THREAD

**Issue by CalTheArsonist** [DashieDev/DoggyTalentsNext#95]
(Version 1.18.25)

The crafting and smelting recipes don't seem to be working.

![image](https://github.com/user-attachments/assets/63c18db0-2fdd-40b4-8641-2b028d4c6495)
![image](https://github.com/user-attachments/assets/396ecb94-527c-41d9-866d-9357b32c5bff)
![image](https://github.com/user-attachments/assets/d96878ea-72fa-4fe3-a0a2-0be2bbbc4b76)

**Comment by DashieDev** [comment]
Oh god..... Lemme take a look in this asap

**Comment by DashieDev** [comment]
Uh it still craftable on my side ......... Perhaps a mod conflict maybe .......... 
![image](https://github.com/user-attachments/assets/13bb25fe-4686-4392-a1fc-6b52b0fc0af8)

**Comment by CalTheArsonist** [comment]
I updated Fabric API and Forge Config API Port and it seems to be working now ¯\_(ツ)_/¯ Very strange
