### ISSUE TITLE
Incompatible with Forbidden & Arcanus' "Quantum Catcher"

### ISSUE THREAD

**Issue by Agret-Brisignr** [DashieDev/DoggyTalentsNext#96]
Describe the bug
Entity: doggytalents:dog, once inside Forbidden & Arcanus' quantum catcher, is unable to be released

To Reproduce

    Convert a wolf into doggytalents:dog via training treat
    Use a quantum catcher on entity doggytalents:dog
    Attempt to release doggytalents:dog from catcher

Expected behavior

When attempting to release doggytalents:dog, the entity should be summoned

Screenshots
N/A

Versions
    DoggyTalentsNext: 1.19.2-1.18.18
    Forbidden & Arcanus: 1.19.2-2.1.5
    Valhelsia Core: 1.19.2-0.5.0
    Forge: 43.3.8

**Comment by DashieDev** [comment]
This is expected behaviour
https://doggytalentsnext.wiki.gg/wiki/FAQ#About_Compatibility_between_DTN_and_a_3rd-party_mod's_feature_that_stores_the_dog_in_something._(eg._Carry_On,_Portable_Mobs,_Mobs_in_a_Bucket,_Ender_Lead,...)

**Comment by Agret-Brisignr** [comment]
> This is expected behaviour https://doggytalentsnext.wiki.gg/wiki/FAQ#About_Compatibility_between_DTN_and_a_3rd-party_mod's_feature_that_stores_the_dog_in_something._(eg._Carry_On,_Portable_Mobs,_Mobs_in_a_Bucket,_Ender_Lead,...)

My apologies, thank you for the info
